name: Criar Branch para Issue

on:
  issues:
    types:
      - opened

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  create_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Verificar Issue e Criar Branch
        id: create-branch
        run: |
          issue_title="${{ github.event.issue.title }}"
          branch_name="issue/${issue_title// /-}"
          git checkout -b "$branch_name"
          ls
          dir
          cd ${{ github.event.repository.name }}/
          git push origin "$branch_name"
          echo "::set-output name=branch::$branch_name"
        shell: bash

      - name: Associar Branch com Issue
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          issue_number="${{ github.event.issue.number }}"
          branch_name="${{ steps.create-branch.outputs.branch }}"
          api_url="https://api.github.com/repos/${{ github.repository }}/issues/${issue_number}/comments"
          comment_body="A branch foi criada: [${branch_name}](${{ github.repository }}/tree/${branch_name})"
          curl -X POST -s -H "Authorization: token $GITHUB_TOKEN" -d "{\"body\":\"$comment_body\"}" "$api_url"

