name: Criar Branch para Issue

on:
  issues:
    types:
      - opened

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  create_branch:
    runs-on: ubuntu-latest

    steps:
        
      - name: Clonar o repositório
        uses: actions/checkout@v2 # Use a ação oficial de checkout do GitHub
        with:
          ref: main # A branch principal que você deseja clonar
          
      - name: Verificar Issue e Criar Branch
        id: create-branch
        run: |
          issue_title="${{ github.event.issue.title }}"
          issue_number="${{ github.event.issue.number }}"
          branch_name="issue/${issue_title// /-}"
          gh issue develop $issue_number  --base main --name ${{ github.event.issue.label }}$branch_name
    #      echo "::set-output name=branch::$branch_name"
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
